server.port=8082
doctor.service.message=Doctor service is running from Config Server
spring.application.name=DOCTOR-SERVICE


management.tracing.sampling.probablity=1.0


management.zipkin.tracing.endpoint=https://localhost:9411/api/v2/spans

db.password=$(DB_PASSWORD)
